spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ragdb
    username: root
    password: admin

  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: deepseek-r1:1.5b
      chat:
        model: deepseek-r1:1.5b
    vectorstore:
      mariadb:
        initialize-schema: true     # auto-create the table for you
        dimensions: 1536            # must match embedding model
        distance-type: COSINE       # or EUCLIDEAN
